const MODE = {
    PLAIN: 'PLAIN',
    OUTLINED: 'OUTLINED',
    CONTAINED: 'CONTAINED',
};

const TYPE = {
    FLOATING: 'FLOATING',
    STICKY_TOP: 'STICKY_TOP',
    STICKY_BOTTOM: 'STICKY_BOTTOM',
    NORMAL: 'NORMAL',
};

const ICON_POSITION = {
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',
    LEFT: 'LEFT',
    RIGHT: 'RIGHT',
};

const BADGE_POSITION = {
    INNER_LEFT: 'INNER_LEFT',
    INNER_RIGHT: 'INNER_RIGHT',
    INNER_TOP: 'INNER_TOP',
    INNER_BOTTOM: 'INNER_BOTTOM',
    OUTER_TOP_LEFT: 'OUTER_TOP_LEFT',
    OUTER_TOP_RIGHT: 'OUTER_TOP_RIGHT',
    OUTER_BOTTOM_LEFT: 'OUTER_BOTTOM_LEFT',
    OUTER_BOTTOM_RIGHT: 'OUTER_BOTTOM_RIGHT',
};

const BADGE_CORNER_SHAPE = {
    ROUND: 'ROUND',
    SQUARE: 'SQUARE',
};

const SHADOW_LEVEL = {
    LIGHT: 'LIGHT',
    MODERATE: 'MODERATE',
    HEAVY: 'HEAVY',
};

export {
    MODE,
    TYPE,
    ICON_POSITION,
    BADGE_POSITION,
    BADGE_CORNER_SHAPE,
    SHADOW_LEVEL,
};
